name: floodrisk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip

  # Core scientific libraries
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn

  # Geospatial / Remote Sensing
  - geopandas
  - rasterio
  - shapely
  - fiona
  - pyproj
  - earthengine-api
  - geemap

  # Notebooks
  - jupyter
  - notebook
  - ipykernel

  # Utils
  - requests
  - tqdm
  - pillow

  # Install from pip (latest versions)
  - pip:
      # PyTorch
      - torch
      - torchvision
      - torchaudio
      - pytorch-lightning
      - segmentation-models-pytorch

      # TensorFlow / Keras
      - tensorflow
      - keras

      # Image Processing
      - albumentations
      - opencv-python
      - scikit-image
